import numpy as np
import pandas as pd
import matplotlib
matplotlib.use('TkAgg')  # Or 'Agg', 'Qt5Agg', depending on your system
import matplotlib.pyplot as plt

# Solar Panel Parameters
P_max = 321  # Nominal power in Watts (NOCT)
I_NOCT = 800  # Light intensity at NOCT in W/m^2
temperature_coefficient = -0.0029  # Temperature coefficient (per °C)
T_ref = 20  # Reference temperature in °C (NOCT)
amount_of_panels = 385  # Amount of solar panels
panel_area = 1.6 #(check)

# Preprocess CSV
def preprocess_csv(file_path, output_path):
    with open(file_path, 'r', encoding='utf-8') as infile, open(output_path, 'w', encoding='utf-8') as outfile:
        for line in infile:
            # Replace commas with dots and empty fields with NaN
            line = line.replace(',', '.').replace('""', 'NaN')
            outfile.write(line)

# File paths
input_file = 'report.csv'
processed_file = 'processed_report.csv'

# Preprocess the CSV file
preprocess_csv(input_file, processed_file)

# Load the processed CSV using pandas
df = pd.read_csv(processed_file, delimiter=';', parse_dates=['time'], dayfirst=True)

# Extract specific columns
time = df['time']  # Parsed as datetime
T_actual = pd.to_numeric(df['Buitentemperatuur'], errors='coerce')  # Outdoor temperature
#light_intensity = pd.to_numeric(df['Lichtintensiteit zuid'], errors='coerce')  # Light intensity
global_radiation = pd.to_numeric(df['Globale Radiate'], errors='coerce') # Global Radiation
export_limit = pd.to_numeric(df['Export beperking'], errors='coerce')  # Export limit as percentage

# Handle missing data
T_actual.fillna(method='ffill', inplace=True)  # Fill temperature NaNs with the previous value
#light_intensity.fillna(0, inplace=True)  # Replace missing light intensity with 0
export_limit.fillna(100, inplace=True)  # Replace missing export limits with 100%
global_radiation.fillna(0, inplace=True) # Replace missing global radiation with 0

# For the sun, convert lux to W/m^2: 1 lux = 0.0079 W/m^2 and multiply by amount of panels
#light_intensity = light_intensity * 0.0079 * 1000 * amount_of_panels

# Calculate Power Output per panel
P_raw_panel = P_max * (global_radiation / I_NOCT)  # Power generated by a single panel

# Adjust for temperature effects
P_raw_panel = P_raw_panel * (1 + temperature_coefficient * (T_actual - T_ref))  # Temperature adjustment
P_raw_panel = np.clip(P_raw_panel, 0, None)  # Set negative values to 0

# Scale up to total power for all panels
P_raw = P_raw_panel * amount_of_panels


# Adjust Power Output for Export Limit
export_factor = export_limit / 100.0  # Convert percentage to a multiplier
P_adjusted = P_raw * export_factor  # Apply export limit

# Calculate Energy Outputs
dt = 1 / 12  # Time interval in hours (5-minute intervals = 1/12 hour)
E_raw = np.sum(P_raw) * dt  # Total energy output
E_lost = np.sum(P_adjusted) * dt  # Total energy lost due to export limit

# Display Results and put them in graph
print(f"Total Energy Output: {E_raw:.2f} Wh")
print(f"Total Energy Lost (Due to Export Limit): {E_lost:.2f} Wh")

# Plot Results
plt.figure(figsize=(12, 6))
plt.plot(time, P_adjusted, '-o', label="Misgelopen Energie", markersize=4, color='green')
plt.plot(time, P_raw, '-o', label="Totale Solar output", markersize=4, color='red')
plt.xlabel('Time')
plt.ylabel('Power (W)')
plt.title('Energie van zonnepanelen dat niet opgewekt wordt door export beperking')
plt.grid(True)
plt.legend()
# display end results in graph
#plt.text(time.iloc[0], P_raw.max(), f"Totale Energie: {E_raw:.2f} Wh", fontsize=12, color='red')
plt.text(time.iloc[0], P_adjusted.max(), f"Misgelopen Energie: {E_lost:.2f} Wh", fontsize=12, color='green')

# Improve datetime formatting on x-axis
plt.gcf().autofmt_xdate()
plt.tight_layout()
plt.show()
